const all_events=[
    
    {
        "title": "Comedy Night",
        "days": ["1"],
        "tagline": "Karunesh Talwar",
        "desc": "Mumbai based stand-up comedian Karnunesh Talwar started out as script writer for the massively popular AIB Comedy Group.<br/><br/>Equipped with observational skills sharp as a blade and language skills of a scholar, his commentary on societal idiosyncrasies, with has garnered him a massive following on YouTube with over 700k followers.<br/><br/>We promise you a riot of a night with gut busting laughter and comedy which will set the stage for the whole fest experience at NITK!",
        "location": "SJA NITK",
        "date_time": "10.00 PM",
        "image": "assets/img/comedy_night.jpeg",
        "type": "Pro_Show",
        "registration_link": "https://dare2compete.com/p/comedy-night-with-karunesh-talwar-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-270606"
    },
    {
        "title": "Fusion Night",
        "days": ["2"],
        "tagline" : "The Pineapple Express, The Nonviolinist",
        "desc": "Incident '22 brings to you the concert of a life time with Banglore-based fusion band Pineapple Express! Pineapple Express brings life to the crowd with their progressive fusion take on Carnatic, Rock and Experimental Electronic music. From their debut in 2016, Pineapple Express has shot to fame after their hit single 'Money' on Kappa TV, and now it's time they bring their swagger to Incident '22!",
        "location": "NITK Main Ground",
        "date_time": "8PM onwards",
        "image": "assets/img/day1.jpg",
        "type": "Pro_Show",
        "registration_link": "https://dare2compete.com/p/fusion-night-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-270624"
    },
    {
        "title": "Encore Night",
        "days": ["4"],
        "tagline" : "Benny Dayal, Lohar the Blacksmiths",
        "desc": "Incident '22 brings to you the concert of a life time with one of India's top playback singers, Benny Dayal! He is a prominent singer in Hindi, Tamil, Telugu, Malayalam, Kannada, Gujarati and more. Benny Dayal rose to fame in 2009 with his hit song 'Rehna Tu' from the bollywood movie 'Delhi 6', and now it's time he brings his swagger to Incident '22!<br/><br/>The 6 piece band - Lohar The Blacksmiths was formed by friends Aritra, Sumukh, Vikas and Rakshith in 2019. Their band focused on covering Indian Classical and Multilingual Rock Music. Their music has won them several Battles of Bands and they have performed over 50 live concerts. Eventually, they were joined by Anoop and Sanath who make the current lineup for this up and coming indie rock band. Now they are performing on Day 3 at the Inci Pronites! The hype is absolutely on!",
        "location": "NITK Main Ground",
        "date_time": "8PM onwards",
        "image": "assets/img/Day3.jpg",
        "type": "Pro_Show",
        "registration_link": "https://dare2compete.com/p/encore-night-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-268769"
    },
    {
        "title": "Hogathon",
        "days": ["3"],
        "tagline" : "Attentinon all foodies!🍔🤤 The Realm shall put your gluttony to the test at the Hogathon 2022. ",
        "desc": "Join the others in this epic competition where the one who shall chow down on the food in the least time shall be crowned the victor!",
        "location": "Chem Block Road",
        "date_time": "12PM-2PM",
        "image": "assets/img/hogathon.jpg",
        "type": "Specials"
    },
    {
        "title": "Adventure Zone",
        "days": ["4"],
        "tagline" : "Adventure Time!",
        "desc": "Got the hots for the thrills of adventure? We present to you the <b>Adventure Zone</b>, so that the junta gets the full Incident Experience™️. With games such as: <br/><br/> <b>Mechanical Bull: </b> Can you last 8 seconds? 😏 On the bucking animatronic bull, we mean. We will put your rodeo skills to the test here. <br/><br/> <b>Slippery Soccer:</b> it's slippy football, what more do you need? Come with your friends to have a jolly time sliding around, playing the most popular sport in the world. <br/><br/><b>Archery:</b> If you had the urge to test your archery skills when the Olympics were on, thinking that hmmmm I could do this, boy do we have an opportunity for you!<br/><br/><b>Bubble Ball:</b> Don the big bubble and go wild. Ram into your friends like a truck and get ragdolled yourself! It's anybody's game!<br/><br/><b>Sumo Wrestling:</b> Sumo. Wrestling. Wear comically oversized sumo outfits and defeat your friends in the way of the Rikishi!",
        "location": "Old Chemical Dept Road, near Suprabha",
        "date_time": "10AM-5PM",
        "image": "assets/img/AdventureZone.jpg",
        "type": "Specials"
    },
    {
        "title": "Chai Point",
        "days": ["2", "3", "4"],
        "tagline" : "Come for the Kadak Chai, stay for the Kadak Artistry",
        "desc": "ChaiPoint is our effort at discovering and supporting local talent. Be it stand up or poetry, instrumental or vocational, our stage is open for all. While the patrons relish a steaming cup of chai, the artists get to exhibit their forte. If you’re a budding artiste holding back for the right opportunity or someone who just wants to kickback and enjoy a pleasant evening, ChaiPoint is the venue for you.",
        "location": "New Chemical Building ",
        "date_time": "4PM-8PM",
        "image": "assets/img/ChaiPoint.jpg",
        "type": "Specials",
        "link":"https://docs.google.com/document/d/1On_pzgcVUGO1ucN6DqyWvsXkzd54qhuI4yV1vqVeFJg/edit?usp=sharing",
        "registration_link": "https://dare2compete.com/creative-cultural-event/chai-point-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269581"
    },
    // {
    //     "title": "Beach Events",
    //     "days": ["3", "4"],
    //     "tagline" : "A bash at the beach",
    //     "desc": "Missing that blissful feeling you get on beaches during the summer? Come take part in the personalized Beach Events of Inci’22 (Days 2 and 3, 4:30 PM) at NITK’s very own private beach!",
    //     "location": "NITK Beach",
    //     "date_time": "4PM-6:30PM",
    //     "image": "assets/img/moms_magic.jpg",
    //     "type": "Specials"
    // },
    { 
        "title": "Sand Art Competition",
        "days": ["3"],
        "tagline" : "Art of sand",
        "desc": "Artist Forum NITK, in association with Incident 2022, presents you a fun and creative Sand Art Competition during our flagship event Udaan. Be a part of this beach festival with your shovels and quirky ideas! Participants can join in teams of maximum 6 members from 3:00 pm to 6:00pm on 5th of March 2022 at the NITK beach. Get creative and win prizes worth 10k.",
        "location": "NITK Beach",
        "date_time": "3:00 PM-6:00 PM",
        "image": "assets/img/sand.jpeg",
        "type": "Specials",
        "registration_link": "https://forms.gle/ZpTrdA5TMJzMywwB8"
    },
    {
        "title": "Udaan",
        "days": ["3"],
        "tagline" : "The ultimate festival of the year",
        "desc": "The much awaited Udaan '22 is finally here! Mark your calendars for the 5th of March for a fun day at the beach with games, food and stalls lined up just for you. Make a sand castle, or in take part in an intense game of tug-of-war or of course, fly kites with your friends - we got you covered.",
        "location": "NITK Beach",
        "date_time": "4PM-6PM",
        "image": "assets/img/cover3.jpg",
        "type": "Specials"
    },

    {
        "title": "Promenade",
        "subtitle": "Hip Hop Internationals South India Auditions",
        "days": ["4"],
        "tagline" : "A coordination to cadence",
        "desc": "Sure your squad can be the Kings of dance-offs? Incident presents Promenade in association with Hip Hop International India which is our flagship group-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://docs.google.com/document/d/1FO6fXSqYrB93yv-LCcXyPjQtT7X4KT1HPRS6acxXf4Y/edit?usp=sharing",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/Promenade.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/promenade-hiphop-internationals-south-india-auditions-incident-2022-national-institute-of-techno-269242"
    },
    {
        "title": "Step up Duet",
        "subtitle": "Hip Hop Internationals South India Auditions",
        "days": ["4"],
        "tagline" : "It's time to tango!",
        "desc": "Incident presents Step up Duet in association with Hip Hop International India which is our flagship duet-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://docs.google.com/document/d/1lsC_l1WI50iEJnnULosZKGW32e-zwQ3-PIDvVPYINGM/edit?usp=sharing",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/Duet.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/step-up-duet-hip-hop-international-south-india-auditions-incident-2022-national-institute-of-tec-269229"
    },
    {
        "title": "Step up Solo",
        "subtitle": "Hip Hop Internationals South India Auditions",
        "days": ["4"],
        "tagline" : "Prepare to dance your ass off!",
        "desc": "Incident presents Step up Solo in association with Hip Hop International India which is our flagship solo-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://docs.google.com/document/d/1ZAlsrnaI3eVYwilRHYyrIfGguKToiX0f2hNICUOzrLo/edit?usp=sharing",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/solo.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/step-up-solo-hip-hop-internationals-south-india-auditions-incident-2022-national-institute-of-te-269228"
    },
    {
        "title": "Askerville Manor-Travel and Exploration Quiz",
        "days": ["4"],
        "tagline" : "The wind is rising",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "6th March, 11.30PM-12.30PM and 1PM-3PM",
        "image": "assets/img/Wind_is_rising.jpg",
        "type": "Lit",
        "registration_link": "https://dare2compete.com/quiz/askerville-manor-travel-and-exploration-quiz-incident-2022-national-institute-of-technology-karnataka-nitk-surathka-269223"
    },
    {
        "title": "Askerville Manor-General Quiz",
        "days": ["2"],
        "tagline" : "Welcome to Knowledgeville",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "4th March 2022, 12PM-1PM and 3PM-5PM",
        "image": "assets/img/Cirque.jpg",
        "type": "Lit",
        "registration_link": "https://dare2compete.com/quiz/askerville-manor-general-quiz-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269212"
    },
    {
        "title": "Askerville Manor-Realm of Reveries Quiz",
        "days": ["3"],
        "tagline" : "Trivia Teleportation",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "5th March 2022, 11AM-12PM and 2PM-4PM",
        "image": "assets/img/Requizem.jpg",
        "type": "Lit",
        "registration_link": "https://dare2compete.com/quiz/askerville-manor-realm-of-reveries-quiz-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269216"
    },
    {
        "title": "Raaga Rhapsody",
        "days": ["2"],
        "tagline": "Pure, raw, strong and moving",
        "desc": "Pure, raw, strong and moving. INCIDENT 2022 Musicals brings to you, Raaga-Rhapsody, the solo vocals competition. From Ballads to Alaaps, this event gives you a stage to wow us with your singing and a chance to win the title of “Voice of Inci”.",
        "link": "https://docs.google.com/document/d/1CnDneReEvqK483zO2Aa4G4fLZ4E1euT9c4Vu6o-z_tI/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 1:30 PM Onwards",
        "image": "assets/img/Raaga.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/raaga-rhapsody-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269235"
    },
    {
        "title": "Biz Cosplay",
        "days": ["4"],
        "tagline": "Pitching meets Pop Culture!",
        "desc": "A first-of-its-kind event that combines business acumen with pop culture!",
        "link": "https://docs.google.com/document/d/1Wz8MfwpQzzYvZUwm2e_PktDwOumSF4FBtsYjh8NxAXw/edit?usp=sharing",
        "location": "Online",
        "date_time": "6th March 2022, 10:00 AM Onwards",
        "image": "assets/img/Biz Cosplay.jpg",
        "type": "Biz",
        "registration_link": "https://forms.gle/ga5rfrrS6b19DQD19"
    },
    {
        "title": "Case Crunch",
        "days": ["3"],
        "tagline": "No risk and no loss, the only case opportunity you will come across.",
        "desc": "Incident NITK in association with E-Cell NITK invites you to “Case Crunch”, an extreme Case Study competition, which will bring out some of the best ideas in your mind and challenge your entrepreneurial spirit. Dive into the sea of opportunities that is Case Crunch and stand a chance to win prizes worth 20k!",
        "link": "https://docs.google.com/document/d/1MDTtTXMKgvktMtYFw25-sPgQgeTmVcXqsAwMyHGRFBU/edit?usp=sharing",
        "location": "Online and Offline for final",
        "date_time": "5th March 2022, 9:00 AM - 5:00 PM",
        "image": "assets/img/case_crunch.jpg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/competition/case-crunch-national-institute-of-technology-karnataka-nitk-surathkal-267355?lb=fc3nEzA"
    },
    {
        "title": "Crypto Knight",
        "days": ["2"],
        "tagline": "Put on your shining armour and test your crypto mettle",
        "desc": "BizEvents from Team Incident aims to get students familiarised and exposed to the cryptocurrency market with real-world trading without actually investing their own money.",
        "link": "https://docs.google.com/document/d/1Y_AC4eBmf_C9Zu4xTu00p_l81AhoTeB8hM5ih-7GzYc/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/Crypto knight.jpg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/competition/mock-crypto-trading-e-summit-22-national-institute-of-technology-karnataka-nitk-surathkal-252886"
    },
    {
        "title": "Pulse",
        "days": ["2"],
        "tagline": "Western battle of bands!",
        "desc": "Incident’s coveted inter-college Battle of Bands, Pulse attracts talent from all over the country and showcases the best music you may have yet heard.",
        "link": "https://docs.google.com/document/d/1I6YPyxz2CEEzXJRHBcOGzQiPIfFvYg9uAQa4d16oTU0/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 9:00 AM Onwards",
        "image": "assets/img/Pulse.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/pulse-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269218"
    },
    {
        "title": "Toastmasters Speech And Rhetoric Contest",
        "days": ["3"],
        "tagline": "",
        "desc": "This contest aims at giving a stage where all are allowed to compete and voice their thoughts and the winner will be crowned as the TSAR. ",
        "link": "https://docs.google.com/document/d/10yhClWp2u9YxQa7bCQMDlHvgtXU3cw8oJEV_6ezVePM/edit?usp=sharing",
        "location": "SOM Seminar Hall",
        "date_time": "5th March 2022, 1PM - 3PM",
        "image": "assets/img/TSAR.jpg",
        "type": "Lit",
        "registration_link": "https://dare2compete.com/creative-cultural-event/toastmasters-speech-and-rhetoric-contest-incident-2022-national-institute-of-technology-karnatak-269243"
    },
    {
        "title": "Tandav",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary group dance",
        "desc": "Incident '22 brings to you the much awaited classical extravaganza Tandav, a team event, where some of the most talented artistes battle it out with prizes worth 30K up for grabs!",
        "link": "https://docs.google.com/document/d/1bplbnNvUfBglps2ft5KHoTqheOsvqyNV7O6KkB6NwDo/edit?usp=sharing",
        "location": "SJA, NITK",
        "date_time": "5th March 2022, 9:00 AM Onwards",
        "image": "assets/img/Tandav.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/tandav-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269172"
    },
    {
        "title": "Nrithya",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary solo dance",
        "desc": "Incident '22 brings to you Nritya, the Classical Eastern and Contemporary Solo Dance Competition where the best dancers across the country morph the diverse ethnic Indian Dance forms into unforgettable performances with prizes upto 13K up for the taking.",
        "link": "https://docs.google.com/document/d/1A1JPlI9aziwBWdQDsrjIZiZkzJ6SbHmNz5Xep-T4Cu8/edit?usp=sharing",
        "location": "SJA, NITK",
        "date_time": "5th March 2022, 12:00 PM onwards",
        "image": "assets/img/Nrithya.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/nrithya-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269225"
    },
    {
        "title": "Dance Workshop",
        "days": ["3"],
        "tagline": "Elevate Your Dance.",
        "desc": "Dance Workshop is a warm and inviting space for youth to enjoy and learn the art of dance.",
        "link": "https://docs.google.com/document/d/1BaoALbjW2NhpbDThiBBGoNhH7S8MKNgfDytsN2ITmJs/edit",
        "location": "Seminar Hall, Mechanical Dept, NITK",
        "date_time": "5th March 2022, 9:00 AM onwards",
        "image": "assets/img/og_image.jpeg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/workshop/dance-workshop-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269232"
    },
    {
        "title": "Duco",
        "days": ["2"],
        "tagline": "we are not led, we lead",
        "desc": "The Best Management Team is that golden ticket to showcase your talents, creativity and abilities in terms of 5 M's of management which will help you to gain knowledge and improvise your expertise.",
        "link": "https://docs.google.com/document/d/1oEE_iq6ioDohnGAy_T-D3vXNH5CqVdUnVU9YV77EwKU/edit?usp=sharing",
        "location": "LHC-C, NITK",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/Duco.jpg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/creative-cultural-event/duco-incident-2022-national-institute-of-technology-karnataka-nitk-surathkal-269239"
    },
    {
        "title": "Zodiacus",
        "days": ["2"],
        "tagline": " A Realm Of Marketing",
        "desc": "Always sharing memes and decoding the latest trending ads? Well, why not win some prizes while you're at it!",
        "link": "https://docs.google.com/document/d/17CoOiwDDL1M6hT5BYrl9OulbSxBiLo4P3Ud5j9bqw4Y/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/Zodiacus.jpg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/creative-cultural-event/zodiacus-best-management-team-bizwaves-incident-2022-national-institute-of-technology-karnataka--269234"
    }
]
