const all_events=[
    {
        "title": "Promenade (Hip Hop Internationals South India Auditions)",
        "days": ["4"],
        "tagline" : "A coordination to cadence",
        "desc": "Sure your squad can be the Kings of dance-offs? Incident presents Promenade in association with Hip Hop International India which is our flagship group-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://docs.google.com/document/d/1FO6fXSqYrB93yv-LCcXyPjQtT7X4KT1HPRS6acxXf4Y/edit?usp=sharing",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/Promenade.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268371/register"
    },
    {
        "title": "Step up Duet (Hip Hop Internationals South India Auditions)",
        "days": ["4"],
        "tagline" : "It's time to tango!",
        "desc": "Incident presents Step up Duet in association with Hip Hop International India which is our flagship duet-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://dare2compete.com/creative-cultural-event/step-up-duet-hip-hop-international-south-india-auditions-incident-2022-national-institute-of-tec-268715",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/Duet.jpg",
        "type": "Music_Dance"
    },
    {
        "title": "Step up Solo (Hip Hop Internationals South India Auditions)",
        "days": ["4"],
        "tagline" : "Prepare to dance your ass off!",
        "desc": "Incident presents Step up Solo in association with Hip Hop International India which is our flagship solo-dance event on the 6th of March 2022.\n Suit up and dance your soles off to achieve hip-hop glory!",
        "link": "https://docs.google.com/document/d/1ZAlsrnaI3eVYwilRHYyrIfGguKToiX0f2hNICUOzrLo/edit?usp=sharing",
        "location": "Silver Jubilee Auditorium",
        "date_time": "6th March, 9AM onwards",
        "image": "assets/img/solo.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268322/register"
    },
    {
        "title": "Askerville Manor-Travel and Exploration Quiz",
        "days": ["4"],
        "tagline" : "The wind is rising",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "6th March, 11.30PM-12.30PM and 1PM-3PM",
        "image": "assets/img/og_image.jpeg",
        "type": "Lit"
    },
    {
        "title": "Askerville Manor-General Quiz",
        "days": ["2"],
        "tagline" : "Welcome to Knowledgeville",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "4th March 2022, 12PM-1PM and 3PM-5PM",
        "image": "assets/img/og_image.jpeg",
        "type": "Lit"
    },
    {
        "title": "Askerville Manor-Realm of Reveries Quiz",
        "days": ["3"],
        "tagline" : "Trivia Teleportation",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "5th March 2022, 11AM-12PM and 2PM-4PM",
        "image": "assets/img/og_image.jpeg",
        "type": "Lit"
    },
    {
        "title": "Raaga Rhapsody",
        "days": ["2"],
        "tagline": "Pure, raw, strong and moving",
        "desc": "Pure, raw, strong and moving. INCIDENT 2022 Musicals brings to you, Raaga-Rhapsody, the solo vocals competition. From Ballads to Alaaps, this event gives you a stage to wow us with your singing and a chance to win the title of “Voice of Inci”.",
        "link": "https://docs.google.com/document/d/1CnDneReEvqK483zO2Aa4G4fLZ4E1euT9c4Vu6o-z_tI/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 1:30 PM Onwards",
        "image": "assets/img/Raaga.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268371/register"
    },
    {
        "title": "Biz Cosplay",
        "days": ["4"],
        "tagline": "Pitching meets Pop Culture!",
        "desc": "A first-of-its-kind event that combines business acumen with pop culture!",
        "link": "https://docs.google.com/document/d/1Wz8MfwpQzzYvZUwm2e_PktDwOumSF4FBtsYjh8NxAXw/edit?usp=sharing",
        "location": "Online and Offline for final",
        "date_time": "6th March 2022, 10:00 AM Onwards",
        "image": "assets/img/og_image.jpeg",
        "type": "Biz"
    },
    {
        "title": "Case Crunch",
        "days": ["3"],
        "tagline": "No risk and no loss, the only case opportunity you will come across.",
        "desc": "Incident NITK in association with E-Cell NITK invites you to “Case Crunch”, an extreme Case Study competition, which will bring out some of the best ideas in your mind and challenge your entrepreneurial spirit. Dive into the sea of opportunities that is Case Crunch and stand a chance to win prizes worth 20k!",
        "link": "https://docs.google.com/document/d/1MDTtTXMKgvktMtYFw25-sPgQgeTmVcXqsAwMyHGRFBU/edit?usp=sharing",
        "location": "Online and Offline for final",
        "date_time": "5th March 2022, 9:00 AM - 5:00 PM",
        "image": "assets/img/case crunch.jpg",
        "type": "Biz"
    },
    {
        "title": "Crypto Knight",
        "days": ["2"],
        "tagline": "Put on your shining armour and test your crypto mettle",
        "desc": "BizEvents from Team Incident aims to get students familiarised and exposed to the cryptocurrency market with real-world trading without actually investing their own money.",
        "link": "https://docs.google.com/document/d/1MDTtTXMKgvktMtYFw25-sPgQgeTmVcXqsAwMyHGRFBU/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/Crypto knight.jpg",
        "type": "Biz"
    },
    {
        "title": "Pulse",
        "days": ["2"],
        "tagline": "",
        "desc": "Incident’s coveted inter-college Battle of Bands, Pulse attracts talent from all over the country and showcases the best music you may have yet heard.",
        "link": "https://docs.google.com/document/d/1I6YPyxz2CEEzXJRHBcOGzQiPIfFvYg9uAQa4d16oTU0/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 9:00 AM Onwards",
        "image": "assets/img/Pulse.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268308/register"
    },
    {
        "title": "Toastmasters Speech And Rulebook Contest",
        "days": ["3"],
        "tagline": "",
        "desc": "This contest aims at giving a stage where all are allowed to compete and voice their thoughts and the winner will be crowned as the TSAR. ",
        "link": "https://docs.google.com/document/d/10yhClWp2u9YxQa7bCQMDlHvgtXU3cw8oJEV_6ezVePM/edit?usp=sharing",
        "location": "SOM Seminar Hall",
        "date_time": "5th March 2022, 1PM - 3PM",
        "image": "assets/img/TSAR.jpg",
        "type": "Lit",
        "registration_link": "https://dare2compete.com/competitions/268409/register"
    },
    {
        "title": "Tandav",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary group dance",
        "desc": "Incident '22 brings to you the much awaited classical extravaganza Tandav, a team event, where some of the most talented artistes battle it out with prizes worth 30K up for grabs!",
        "link": "https://docs.google.com/document/d/1bplbnNvUfBglps2ft5KHoTqheOsvqyNV7O6KkB6NwDo/edit?usp=sharing",
        "location": "SJA, NITK",
        "date_time": "5th March 2022, 9:00 AM Onwards",
        "image": "assets/img/Tandav.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268273/register"
    },
    {
        "title": "Nrithya",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary solo dance",
        "desc": "Incident '22 brings to you Nritya, the Classical Eastern and Contemporary Solo Dance Competition where the best dancers across the country morph the diverse ethnic Indian Dance forms into unforgettable performances with prizes upto 13K up for the taking.",
        "link": "https://docs.google.com/document/d/1A1JPlI9aziwBWdQDsrjIZiZkzJ6SbHmNz5Xep-T4Cu8/edit?usp=sharing",
        "location": "SJA, NITK",
        "date_time": "5th March 2022, 12:00 PM onwards",
        "image": "assets/img/Nrithya.jpg",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/competitions/268320/register"
    },
    {
        "title": "Duco",
        "days": ["2"],
        "tagline": "we are not led, we lead",
        "desc": "The Best Management Team is that golden ticket to showcase your talents, creativity and abilities in terms of 5 M's of management which will help you to gain knowledge and improvise your expertise.",
        "link": "https://docs.google.com/document/d/1oEE_iq6ioDohnGAy_T-D3vXNH5CqVdUnVU9YV77EwKU/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/og_image.jpeg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/competitions/268426/register"
    },
    {
        "title": "Zodiacus",
        "days": ["2"],
        "tagline": " A Realm Of Marketing",
        "desc": "Always sharing memes and decoding the latest trending ads? Well, why not win some prizes while you're at it!",
        "link": "https://docs.google.com/document/d/17CoOiwDDL1M6hT5BYrl9OulbSxBiLo4P3Ud5j9bqw4Y/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "assets/img/og_image.jpeg",
        "type": "Biz",
        "registration_link": "https://dare2compete.com/competitions/268429/register"
    }
]